<?php
get_header();
get_template_part('templates/intro_section');
get_template_part('templates/about_section');
get_template_part('templates/testimonials_section');
get_template_part('templates/services_section');
get_template_part('templates/team_section');
get_template_part('templates/promotion_section');
get_footer();
